executors:
  node:
    parameters:
      image:
        type: string
        default: "latest"
    docker:
      - image: circleci/node:<< parameters.image >>-browsers

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore node_modules cache
      keys:
        - yarn-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}

  persist_cache: &persist_cache
    save_cache:
      name: Save node_modules cache
      key: yarn-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache

  bootstrap_and_build: &bootstrap_and_build
    run:
      name: Bootstrap and Build
      command: yarn bootstrap && yarn build

  install_node_modules: &install_node_modules
    run:
      name: Install node modules
      command: yarn --frozen-lockfile

  install_emulators: &install_emulators
    run:
      name: Install emulators
      command: yarn install-emulators

  assert_changed_files: &assert_changed_files
    run:
      name: Assert Changed Files
      command: ./scripts/assert-changed-files.sh "packages/*|.circleci/*"

  run_tests: &run_tests
    run:
      name: Run tests
      command: yarn test:ci
      environment:
        DEBUG: "*"

  attach_to_bootstrap: &attach_to_bootstrap
    attach_workspace:
      at: packages

  ignore_master: &ignore_master
    filters:
      branches:
        ignore:
          - master

  ignore_docs: &ignore_docs
    filters:
      branches:
        ignore:
          - /docs.+/
          - /blog.+/

  test_template: &test_template
    steps:
      - checkout
      - <<: *assert_changed_files
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *install_emulators
      - <<: *persist_cache
      - <<: *attach_to_bootstrap
      - <<: *run_tests

version: 2.1

jobs:
  bootstrap_v16:
    executor:
      name: node
      image: "16"
    steps:
      - checkout
      - <<: *assert_changed_files
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - <<: *bootstrap_and_build
      - persist_to_workspace:
          root: packages
          paths:
            - "*"

  bootstrap_v14:
    executor:
      name: node
      image: "14"
    steps:
      - checkout
      - <<: *assert_changed_files
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - <<: *bootstrap_and_build
      - persist_to_workspace:
          root: packages
          paths:
            - "*"

  lint:
    executor:
      name: node
      image: "14"
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - run: yarn lint

  unit_tests_node16:
    executor:
      name: node
      image: "16"
    <<: *test_template

  unit_tests_node14:
    executor:
      name: node
      image: "14"
    <<: *test_template

workflows:
  version: 2
  build-test:
    jobs:
      - lint
      - bootstrap_v16
      - unit_tests_node16:
          <<: *ignore_docs
          requires:
            - bootstrap_v16
      - bootstrap_v14:
          requires:
            - unit_tests_node16
      - unit_tests_node14:
          <<: *ignore_docs
          requires:
            - bootstrap_v14
